// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbwsbddxsgmradnpahmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRid3NiZGR4c2dtcmFkbnBhaG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MjA3NDYsImV4cCI6MjA1NzI5Njc0Nn0.e96tu3yCEFw3KfFWSN66FcIrXhgjCwn23pRxhKPdLnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);